# Generated by Django 5.0.4 on 2024-04-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_reg', '0002_auto_20191219_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorlist',
            name='home_address',
        ),
        migrations.AddField(
            model_name='donorlist',
            name='town',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
