# Generated by Django 5.0.4 on 2024-05-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_images'),
        ),
    ]
