# Generated by Django 5.0.4 on 2024-05-05 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_contactus_logo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='description',
        ),
    ]
