# Generated by Django 5.0.4 on 2024-05-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0004_contactus_display_contact_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='display_contact_info',
        ),
    ]
