# Generated by Django 5.0.4 on 2024-06-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0005_remove_contactus_display_contact_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('display_contact_info', models.TextField(blank=True, null=True)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='contact/')),
            ],
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
