# Generated by Django 5.0.4 on 2024-06-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0006_contactdetails_delete_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='contact_images')),
            ],
        ),
        migrations.DeleteModel(
            name='ContactDetails',
        ),
    ]
