# Generated by Django 5.0.6 on 2024-06-12 07:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0007_contactus_delete_contactdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('display_contact_info', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='contact/')),
            ],
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
