# Generated by Django 5.0.4 on 2024-05-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_images'),
        ),
    ]
